{% set name = "glue-qt" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d3e8aa2e1f4092dfe8158523a4c9508f0759a400e8cca8a711669361ce23e883

build:
  entry_points:
    - glue = glue_qt.main:main
  script: {{ PYTHON }} -m pip install . -vv
  string: win_pyh{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [win]
  string: unix_pyh{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [unix]
  number: 0
  osx_is_app: true  # [osx]

requirements:
  host:
    - python
    - setuptools-scm
    - pip
  run:

    # The following is needed to make sure that the package works as a GUI
    # application (glue needs to be run with python.app, not python)
    - python.app  # [osx]

    - python
    - glue-core >=1.15.0
    - numpy >=1.17
    - matplotlib-base >=3.2
    - scipy >=1.1
    - echo >=0.6
    - astropy-base >=4.0
    - setuptools >=30.3.0
    - qtpy >=1.9
    - ipython >=4.0
    - ipykernel >=4.0,!=5.0.0,!=5.1.0
    - qtconsole >=4.3,!=5.4.2
    - pvextractor >=0.2
    - importlib-resources >=1.3
    - importlib-metadata >=3.6
    - pyqt
test:
  imports:
    - glue_qt
    - glue_qt.app
  commands:
    - pip check
    - glue --help
    - glue --version
  requires:
    - pip

# NOTE: we deliberatey do NOT include an app entry here, because we instead do this
# in the glueviz meta-package (we don't want glue to appear twice in the navigator)

about:
  home: http://glueviz.org
  summary: Multidimensional data visualization across files
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - astrofrog
